volumes:
 prometheus-data:
  driver: local
 grafana-data:
  driver: local

networks:
 monitoring_net:
  driver: bridge

services:
 prometheus:
  image: docker.io/prom/prometheus:v3.1.0
  container_name: prometheus
  ports:
   - 9090:9090
  command: '--config.file=/etc/prometheus/prometheus.yaml'
  volumes:
   - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
   - prometheus-data:/prometheus

  networks:
   - monitoring_net
  restart: unless-stopped
 grafana:
  image: docker.io/grafana/grafana-oss:11.4.0
  container_name: grafana
  ports:
   - '3000:3000'
  volumes:
   - grafana-data:/var/lib/grafana
   - ./grafana/provisioning:/etc/grafana/provisioning

  env_file:
   - ./grafana/.env

  networks:
   - monitoring_net
  # restart: unless-stopped

 node_exporter:
  image: quay.io/prometheus/node-exporter:latest
  container_name: node_exporter
  command:
   - '--path.rootfs=/host'
  restart: unless-stopped
  volumes:
   - './:/host:ro,rslave'

  networks:
   - monitoring_net

 cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.51.0
  container_name: cadvisor
  ports:
   - 8080:8080
  volumes:
   - /:/rootfs:ro
   - /run:/run:ro
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
   - /dev/disk/:/dev/disk:ro

  networks:
   - monitoring_net
  devices:
   - /dev/kmsg
  privileged: true
  restart: unless-stopped

 blackbox:
  image: prom/blackbox-exporter:v0.25.0
  container_name: blackbox
  ports:
   - '9115:9115'
  volumes:
   - ./blackbox/blackbox.yaml:/etc/blackbox/blackbox.yaml

  networks:
   - monitoring_net
  command:
   - --config.file=/etc/blackbox/blackbox.yaml
  restart: unless-stopped
