global:
 scrape_interval: 15s

scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
    - targets: ['localhost:9090']

 - job_name: 'node_exporter'
   static_configs:
    - targets: ['node_exporter:9100']

 - job_name: 'api_metrics'
   static_configs:
    - targets: ['host.docker.internal:5001']

 - job_name: 'cadvisor'
   static_configs:
    - targets: ['cadvisor:8080']

 - job_name: 'blackbox'
   metrics_path: /probe
   params:
    module: [http_2xx]
   static_configs:
    - targets:
       - 44.196.138.65:3001

       - 44.196.138.65:5001/metrics

   relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
