services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', '/opt/bitnami/scripts/postgresql/healthcheck.sh']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
